version: "3.9"
services:
  app:
    container_name: {CONTAINER_NAME}
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - {PROXY_PORT}:80
    env_file:
      - ./env/dev.env
    volumes:
      - .:/app
